services:
  - type: web
    name: waist-measurement-app  # Unique name for your service
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade  # Apply database migrations if using Flask-Migrate
    startCommand: gunicorn main:app  # Start the Flask app with Gunicorn
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: waist-db  # Name of the database service
          property: connectionString  # Automatically set by Render
      - key: SECRET_KEY
        generateValue: true  # Generate a secure secret key for Flask
      - key: LANGUAGES
        value: "en,tr"  # Supported languages for Flask-Babel
      - key: BABEL_DEFAULT_LOCALE
        value: "en"  # Default language for Flask-Babel
databases:
  - name: waist-db  # Database service name
    databaseName: waist_db  # Database name
    user: admin  # Default user
    services:
  - type: web
    name: waist-measurement-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py  # Initialize the database schema
    startCommand: gunicorn main:app
